application: oauth-dropins
version: 1
threadsafe: true
api_version: 1
default_expiration: 1d

runtime: python27

libraries:
- name: ssl
  version: latest

handlers:

# static
- url: /static
  static_dir: static

# dynamic
- url: /blogger_v2/.*
  script: blogger_v2.application
  secure: always

- url: .*
  script: app.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|doc|docs|pydocs|python3|ref|samples|tests)/.*

