# https://cloud.google.com/appengine/docs/standard/python3/config/appref

# application: oauth-dropins
# version: 1
default_expiration: 1h
runtime: python37
entrypoint: gunicorn -b :$PORT app:application

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 12

handlers:

- url: /static
  static_dir: oauth_dropins/static

- url: /favicon.ico
  static_files: oauth_dropins/static/favicon.ico
  upload: oauth_dropins/static/favicon.ico

- url: .*
  script: auto
  secure: always
