application: oauth-dropins
version: 1
threadsafe: true
api_version: 1
default_expiration: 1h
runtime: python27

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 12

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest

handlers:

- url: /static
  static_dir: oauth_dropins/static

- url: /favicon.ico
  static_files: oauth_dropins/static/favicon.ico
  upload: oauth_dropins/static/favicon.ico

- url: .*
  script: app.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|docs?|examples?|l|pydocs?|python3|ref|samples?|TAGS|tests?)/.*
