application: oauth-dropins
version: 1
threadsafe: true
api_version: 1
default_expiration: 1d

runtime: python27

handlers:

# static
- url: /static
  static_dir: static

# dynamic
- url: /blogger/.*
  script: blogger.application
  secure: optional
  login: required

- url: /dropbox/.*
  script: dropbox.application
  secure: optional

- url: /facebook/.*
  script: facebook.application
  secure: optional

- url: /instagram/.*
  script: instagram.application
  secure: optional

- url: /googleplus/.*
  script: googleplus.application
  secure: optional
  login: required

- url: /tumblr/.*
  script: tumblr.application
  secure: optional

- url: /twitter/.*
  script: twitter.application
  secure: optional

- url: /wordpress_rest/.*
  script: wordpress_rest.application
  secure: optional

- url: /
  script: app.application
  secure: optional

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
# don't need anything in the submodule subdirs, especially since
# webapp-improved/lib has over 1k files!
- ^(.*/)?(debian|doc|docs|pydocs|python3|ref|samples|tests)/.*

