# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2

jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/google-container-engine/#selecting-a-base-image
      - image: google/cloud-sdk
      - image: circleci/python:2.7

    environment:
      - PYTHONPATH: /usr/lib/google-cloud-sdk/platform/google_appengine

    steps:
      - checkout

      - restore_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements.freeze.txt" }}

      - run:
          name: Base dependencies
          command: |
            apt-get install -y python3 google-cloud-sdk-app-engine-python-extras
            git submodule sync
            git submodule update --init

      - run:
          name: Python 3 dependencies
          command: |
            apt-get update
            apt-get install -y python3-venv python3-dev
            python3 -m venv local3
            . local3/bin/activate
            pip install -r requirements.freeze.txt -c requirements.freeze.py3.txt

      - run:
          name: Test Python 3
          command: |
            . local3/bin/activate
            PYTHONPATH= python3 -m unittest -v oauth_dropins.webutil.tests.test_util

      - run:
          name: Python 2 dependencies
          command: |
            pip install virtualenv
            virtualenv local
            . local/bin/activate
            pip install -r requirements.freeze.txt
            pip install coverage coveralls

      - run:
          name: Test Python 2
          command: |
            . local/bin/activate
            python2 -m coverage run --include=oauth_dropins/webutil/handlers.py,oauth_dropins/webutil/models.py,oauth_dropins/webutil/util.py -m unittest discover -v -p 'test_*.py'
            python2 -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then coveralls || true; fi

      - save_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements.freeze.txt" }}
          paths:
            - "local"
            - "local3"

      - store_artifacts:
          path: /tmp/coverage_html
